name: Leorodney Client CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    defaults:
       run:
         working-directory: ./

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    # Client Dependencies Compatibility
    - uses: actions/checkout@v3
    - name: Node>${{ matrix.node-version }} Client Dependencies Compatibility
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './client/package-lock.json'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test --if-present
